perf-gear-web:
  build: ./
  volumes:
    - "./:/perf-gear-web"
  ports:
    - "3001:4000"
  links:
   - rethinkdb
   
rethinkdb:
    image: rethinkdb:latest
    ports:
      - "8081:8080"
      - "28025:28015"
      - "29025:29015"